### ISSUE TITLE
Problem when trying to build

### ISSUE THREAD

**Issue by cristianofmc** [pantheon-tweaks/pantheon-tweaks#143]
The command 
`io.elementary.switchboard'

is opening elementary os settings

![Screenshot from 2021-12-22 04 45 50](https://user-images.githubusercontent.com/27186405/147037100-87af0bd4-92cc-41c2-bb1f-b98c34d49e88.png)

**Comment by cristianofmc** [comment]
pantheon-tweaks: command not found

**Comment by ryonakano** [comment]
Pantheon Tweaks is a plugin of System Settings in elementary OS; it don't have a independent command, instead you can see the plug named "Tweaks" if you open System Settings (whose command is `io.elementary.switchboard`) after installing it.

Closing as invalid since this doesn't seem to be an issue. Feel free to reopen if I mistook what you want to say.

**Comment by ChildishGiant** [comment]
You should also be able to run `xdg-open settings://tweaks` to open up directly to Tweaks
