### ISSUE TITLE
Feature Request: Top Panel Workspace Scroll

### ISSUE THREAD

**Issue by jsgadas** [pantheon-tweaks/pantheon-tweaks#144]
I'm not sure if it's possible to implement this as an extension, but it would be really handy to be able to change workspaces by mouse scroll over the top panel.

**Comment by ryonakano** [comment]
Thank you for your feature request, but I guess this should be reported against [the repository of the panel](https://github.com/elementary/wingpanel) because it sounds requires code changes in the panel itself; the current panel don't have such option. Pantheon Tweaks just shows hidden & prepared options in the components on Pantheon and we can't take any actions like adding switches if features requested don't exist.

**Comment by jsgadas** [comment]
Thanks for the clarification and suggestion, I will close this issue.
