### ISSUE TITLE
Window control buttons option doesn't change Files tab close button's position

### ISSUE THREAD

**Issue by 1280px** [pantheon-tweaks/pantheon-tweaks#145]
I'm using Windows buttons layout but tab close buttons in Files still aligned to the left:
<img src="https://i.ibb.co/qxNXHsh/sd.png">

Also it'd be nice to make "New Tab" button move to the right when using Windows layout, like it actually located in most Windows apps:
<img src="https://www.deskmodder.de/blog/wp-content/uploads/2020/05/windows-terminal-10.jpg">

**Comment by ChildishGiant** [comment]
The window controls option only affects the close minimise and maximise buttons. The position of the new tab button is controlled solely by files changing this would have to be on that end.

**Comment by 1280px** [comment]
> The window controls option only affects the close minimise and maximise buttons. The position of the new tab button is controlled solely by files changing this would have to be on that end.

What about tab close buttons? The tweak **does** change their location in Epiphany, but not in Files and Terminal

**Comment by ChildishGiant** [comment]
> The tweak does change their location in Epiphany, but not in Files and Terminal

That means that epiphany itself listens to the request to have the controls layed out like that. Much like how steam always has windows control positions on linux, it's down to the app. If you want this fixed that needs to be filed as an issue on [elementary/files](https://github.com/elementary/files)

**Comment by ryonakano** [comment]
> The tweak **does** change their location in Epiphany, but not in Files and Terminal

The tabbar used in the unique apps made for elementary OS (e.g. Files, Terminal, etc.) and used in GNOME apps (e.g. Ephiphany and Nautilus, the GNOME File Manager) are different. The latter uses native tabbar prepared in Gtk or Adwaita, while the former uses the original tabbar elementary developers made to compensate features they need but lacking in the native tabbar. And the position of the close button in the tabbar used in Files, Terminal, etc. are hard-coded and is not something we can change in this project unfortunately.

Sending a code to them through Pull Request might be a solution, but I feel they wouldn't accept it; I think elementary aims to create an OS works and looks good out of box so they would not be interested in tweaking features. But we know a certain number of people who loves elementary OS seek for tweaking so this project exists, although sometimes it might be difficult to make requests from our users true because of these background reasons like hard-coding.
I agree your request is reasonable and necessary for consistency of button layouts. But I'm sorry for not being able to make your request true right now in the scope of this project.

However, the elementary developers might decide to remove their original tabbar and switch to the same tabbar used in GNOME apps in the feature according to https://github.com/elementary/granite/issues/572. This is what it looks like in GNOME (quoted from [here](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.TabBar.html)):

![tab-bar](https://user-images.githubusercontent.com/26003928/150240712-a7adb0b3-4b16-4d27-934a-927f783c735f.png)

And according to the @1280px's first screenshot this respects the window layout chosen in Pantheon Tweaks, so I think what we can do in this project may be just wait for the elementary devs to switch to the same tabbar used in GNOME apps. 🙏

**Comment by ryonakano** [comment]
Also regarding to the New Tab button, there is a discussion in the elementary OS to move it to the end: https://github.com/elementary/granite/issues/413

**Comment by ryonakano** [comment]
Files now switched to `Hdy.TabBar` which used in GNOME too but they hardcoded the position of the tab close button and new tab button:

https://github.com/elementary/files/blob/3553afaba24ec5af844a67d4dedf3d312ad6611f/src/View/Window.vala#L246-L247

which means we have no control of these positions in Pantheon Tweaks so closing this issue as out of scope.
