### ISSUE TITLE
FR: Flatpak

### ISSUE THREAD

**Issue by SephReed** [pantheon-tweaks/pantheon-tweaks#161]
I'm working towards running Pantheon on Fedora and found a great guide on how to do so (https://ryan.himmelwright.net/post/fedora-pantheon-install/)

They explained how to install pantheon-tweaks on Fedora (because they could only find a .deb).

Given the migration over to flatpak for Elementary, plus the support of it all around, I thought it might be nice to let you guys know that having a flatpak would be super awesome.  Even more awesome than this project already is.  :)

If anyone else is interested, feel free to leave a like or comment.

**Comment by ryonakano** [comment]
Hi, thank you for your reporting and sorry for my late reply.

Actually in #5 we're already discussing a way to provide Pantheon Tweaks other than `add-apt-repository` which only available on distributions that adopts apt. However, I think it would be difficult to flatpak Pantheon Tweaks at this time because:

- Pantheon Tweaks is just a plugin of System Settings, so System Setting also needs to be switched to Flatpak too
- Pantheon Tweaks gets/sets hidden system settings, so switching to Flatpak can lose access to them

However, I know many people uses Pantheon Desktop on another distribution like Fedora, so I felt it would be great if we can provide a rpm package of Pantheon Tweaks, host it somewhere (as we do on Launchpad), and these users can install it with a simple command. Then, I found [Monitor](https://github.com/stsdc/monitor) (a system monitor app for Pantheon) uses Copr, which seems to be a counterpart of Launchpad for Fedora: https://copr.fedorainfracloud.org/coprs/stsdc/monitor

@SephReed and @Philip-Scott, what do you think about providing a rpm package of Pantheon Tweaks for people who uses Pantheon on Fedora through Copr?

**Comment by ryonakano** [comment]
Hmm, I installed Pantheon on Fedora 36 and found Pantheon Tweaks was installed at the same time automatically, maybe it's already embedded in the Pantheon Desktop community package for Fedora?

![スクリーンショット 2022-07-18 11 08 53](https://user-images.githubusercontent.com/26003928/179435809-404fb9d0-acce-4d6f-bcb2-89f9b0abde40.png)
