### ISSUE TITLE
No animations tab

### ISSUE THREAD

**Issue by manh9001s** [pantheon-tweaks/pantheon-tweaks#168]
![image](https://user-images.githubusercontent.com/66364838/202881646-1166c075-a89a-4e42-a4f1-f266d8f42741.png)
I dont have the animation tab on my pantheon tweaks and dont know why :(

**Comment by bobby285271** [comment]
Likely because it is removed in #152: 
- https://github.com/pantheon-tweaks/pantheon-tweaks/issues/151

**Comment by ryonakano** [comment]
Yes, we removed the animations pane because Gala, the window manager on Pantheon, began to use values fixed in the source code for animation duration instead of ones that can be configured here since [2019](https://github.com/elementary/gala/commit/50694796d4c8f0ca92517d5a628b0efdf748279c). So these values don't take effect actually for many years before removal.

Closing as "out of scope" since this change is due to the change in Pantheon side, but thank you for using Pantheon Tweaks and reporting this here! We appreciate many people loves Pantheon Tweaks. :heart:
