### ISSUE TITLE
Icons not changed in Applications menu

### ISSUE THREAD

**Issue by rdanter** [pantheon-tweaks/pantheon-tweaks#183]
Since updating to eOS 7.1 the icons setting does not change the appearance of the Applications menu - it always shows the elementary icons. Everywhere3 else (dock, etc) the desired icons are seen as expected.

This was working fine in eOS 7.0 so I am assuming there was a change in how the Applications menu icons are set.

Just for info, I am using the WhiteSur icon set and everything looks pretty amazing. Screenshot attached shows the different icons in use in different areas.

![Screenshot from 2023-10-12 21 31 54](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/2151247/d60dbd7d-14cc-404b-80a8-7eb42274e451)

**Comment by ryonakano** [comment]
> This was working fine in eOS 7.0 so I am assuming there was a change in how the Applications menu icons are set.

Yes, this issue is because now Wingpanel is hardcoded to use elementary icons since https://github.com/elementary/wingpanel/commit/476a9fd47ae5f90c990c30e73a1e5b878a754c64.
You can see that not only Applications Menu but also indicators no longer use customized icons.

Unfortunately there is nothing we can do in Pantheon Tweaks due to hardcode, but if you *really* want to keep the previous appearance and you know git, you can simply clone the source code of Wingpanel and revert the commit above:

![VirtualBox_elementary OS 7 1_14_10_2023_14_31_34](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/6d52cc0f-dc67-4ab4-a0c0-5224557788f1)

But do at your own risk, some texts are not shown as expected like this:

![VirtualBox_elementary OS 7 1_14_10_2023_14_33_33](https://github.com/pantheon-tweaks/pantheon-tweaks/assets/26003928/7a4428fd-46fc-4cd7-aaed-4934b06295cb)

**Comment by rdanter** [comment]
Thanks for the update. This obsession the eOS team has on locking things down is starting to get annoying.  :(

**Comment by ryonakano** [comment]
Closing as out of scope since this is due to a decision in Pantheon itself
