### ISSUE TITLE
Installation without add-apt-repository

### ISSUE THREAD

**Issue by Philip-Scott** [pantheon-tweaks/pantheon-tweaks#5]
From https://github.com/elementary-tweaks/elementary-tweaks/issues/20, but opening here for discussion. It would be nice to have .deb files to install tweaks without having to add the PPA, and also have a way to add auto-updates to it

**Comment by AndreasTNT** [comment]
We could use flatpak. 

Because It's being used by the elementary team.

**Comment by maxie7** [comment]
I agree with AndreasTNT >> "impossible install withput sources", I have en error when I try to add sources!!! 

```
Distributor ID:	Elementary
Description:	elementary OS 6.0 Next
Release:	6.0
Codename:	next

```

**Comment by maxie7** [comment]
For more information. When I try to add repositiory (as they say in the docs) I get this:
```
sudo add-apt-repository ppa:philip.scott/pantheon-tweaks                                                                           ✔  09:41:46   99%  
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
```

**Comment by ryonakano** [comment]
@maxie7 That's because the codename is not set up correctly on elementary OS 6 yet. The elementary devs should fix that issue before the final release though.

For now you can use [these commands](https://github.com/pantheon-tweaks/pantheon-tweaks/issues/43#issuecomment-720077052) to install Pantheon Tweaks on elementary OS 6.

**Comment by ryonakano** [comment]
It would be great if we can provide as Flatpak since providing using PPA sometimes break things like #61 or #68. However, I'm not sure it's possible at the moment because any official plugs are not provided as Flatpak for now. These days elementary devs are working on *flatpaking* their official apps like Calculator, so these plugs might be also *flatpaked* in near feature though.

**Comment by spirulin** [comment]
> It would be great if we can provide as Flatpak since providing using PPA sometimes break things like #61 or #68. However, I'm not sure it's possible at the moment because any official plugs are not provided as Flatpak for now. These days elementary devs are working on _flatpaking_ their official apps like Calculator, so these plugs might be also _flatpaked_ in near feature though.

Now that they packed their apps as flatpaks any chance to see tweaks as flatpak?

**Comment by quentincaffeino** [comment]
Having a flatpak would ve really great since it would allow people like me who don't use elementary but still use pantheon desktop to use this repo without building it themselves.
