### ISSUE TITLE
Consider focusing on contributing more of these options directly to elementary

### ISSUE THREAD

**Issue by hanaral** [pantheon-tweaks/pantheon-tweaks#52]
I have my own thoughts on wacky customisation tools, but they aren't as relevant as the issue I want to outline.
Elementary OS no doubt requires more settings, but those settings need to be implemented in such a way that it makes sense UX-wise for the less-informed target audience of elementary OS _(the general public)_. The target audience is therefore susceptible to installing anything they're told will improve the experience, even if that just makes it more difficult for elementary to create an experience where they can address users' problems with ease.

So what I suggest is that there is even more of an effort to push more of these settings in to the relevant place in the base OS. The fate of this project is entirely up to contributors, but then again so is the fate elementary OS :)

**Comment by ryonakano** [comment]
The purpose of this project is to provide some users who want to customize advanced settings that elementary OS does not support by default. For example, theme settings or some settings for default apps like Videos. These settings are not exposed in elementary OS because of design and their belief; elementary devs want to provide a OS that works out of box and thus they care how users can focus on their tasks and work rather than consuming to setup OS.
However, not 100% people agree this belief; some people thinks "yeah, elementary OS is beautiful, but I'd like to tweak this OS to match my ideal environment" and seeks more advanced settings. This project targets these people.

So we just provide a place to tweak the settings which conflict with the belief of elementary OS. The members of this project are all contributors for elementary OS so we push an effort against the OS itself if we think what we want to implement matches the belief of elementary OS.

**Comment by ryonakano** [comment]
Closing as answered.
