### ISSUE TITLE
Terminal tab buttons placement

### ISSUE THREAD

**Issue by VasilePintilie** [pantheon-tweaks/pantheon-tweaks#60]
Hello. In Terminal, I would really like to have the possibility to move the Add Tab, Close Tab buttons to the right.

**Comment by ryonakano** [comment]
The position of add a new tab and close the tab buttons in Terminal (Code and Files too) is fixed to the left in the source code of a library named "Granite" which these apps use. And the idea to move the new tab button is discussed in the repository of Granite: elementary/granite#413.

I agree it would be great if we can configure position of tab buttons in Pantheon Tweaks, but since it's decided at the source-code level of Granite, we have no control of it. So I'm closing this issue as out-of-scope. Thank you for getting interested in this project and submitting a feature request anyways ☺️
