### ISSUE TITLE
Can't find any option to disable single click to open folder in files app

### ISSUE THREAD

**Issue by xenon86k** [pantheon-tweaks/pantheon-tweaks#76]
There is no option to remove single click to open folder/file in files app like it was in Elementary Tweaks. Looking for a solution. Please help me!

**Comment by ryonakano** [comment]
Unfortunately the option to toggle single click was removed from Pantheon Tweaks because the latest version of Files no longer follows that option. The developers of Files removed that option and instead produced a new function called "mixed-mode"; now users need to perform a single-click to open folders or select a file, and a double-click to open a file.

Thank you for your report, but closing since this option can't be revived in the scope of Pantheon Tweaks.

See also: #65 and #66

**Comment by xenon86k** [comment]
Thanks for your reply! Just one thing, so there is now no option to open folders by double click? If there is way to use double click can you please tell me how to do it?

**Comment by ryonakano** [comment]
Yes, there is now no option to open folders by double click unfortunately😢

**Comment by xenon86k** [comment]
Thanks for your help, have a nice day!
